# Generated by Django 5.0.2 on 2024-02-25 01:39

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyRecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('primary_image_url', models.CharField(max_length=255)),
                ('images_url', models.JSONField(default=apis.models._list)),
                ('ingredients_url', models.JSONField(default=apis.models._list)),
            ],
        ),
    ]
