# Generated by Django 5.0.2 on 2024-02-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrecipebook',
            old_name='ingredients_url',
            new_name='ingredients',
        ),
    ]
